# Generated by Django 3.2.5 on 2021-07-26 23:22

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyDayDates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sunday_date', models.DateField(default=datetime.datetime(2021, 8, 1, 0, 0))),
                ('monday_date', models.DateField(default=datetime.datetime(2021, 8, 2, 0, 0))),
                ('tuesday_date', models.DateField(default=datetime.datetime(2021, 8, 3, 0, 0))),
                ('wednesday_date', models.DateField(default=datetime.datetime(2021, 8, 4, 0, 0))),
                ('thursday_date', models.DateField(default=datetime.datetime(2021, 8, 5, 0, 0))),
                ('friday_date', models.DateField(default=datetime.datetime(2021, 8, 6, 0, 0))),
                ('saturday_date', models.DateField(default=datetime.datetime(2021, 8, 7, 0, 0))),
            ],
        ),
        migrations.CreateModel(
            name='WeeklySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('friday_evening_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='friday_evening_user', to=settings.AUTH_USER_MODEL)),
                ('friday_night_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='friday_night_user', to=settings.AUTH_USER_MODEL)),
                ('monday_evening_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='monday_evening_user', to=settings.AUTH_USER_MODEL)),
                ('monday_night_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='monday_night_user', to=settings.AUTH_USER_MODEL)),
                ('saturday_evening_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='saturday_evening_user', to=settings.AUTH_USER_MODEL)),
                ('saturday_night_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='saturday_night_user', to=settings.AUTH_USER_MODEL)),
                ('sunday_evening_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sunday_evening_user', to=settings.AUTH_USER_MODEL)),
                ('sunday_night_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sunday_night_user', to=settings.AUTH_USER_MODEL)),
                ('thursday_evening_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='thursday_evening_user', to=settings.AUTH_USER_MODEL)),
                ('thursday_night_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='thursday_night_user', to=settings.AUTH_USER_MODEL)),
                ('tuesday_evening_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tuesday_evening_user', to=settings.AUTH_USER_MODEL)),
                ('tuesday_night_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tuesday_night_user', to=settings.AUTH_USER_MODEL)),
                ('wednesday_evening_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='wednesday_evening_user', to=settings.AUTH_USER_MODEL)),
                ('wednesday_night_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='wednesday_night_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='shiftSubmitTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sunday_evening', models.IntegerField(choices=[(0, '0 - Not available'), (1, '1 - Available'), (2, '2 - Preferred ')], default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)], verbose_name='sunday evening 16:00-23:00')),
                ('sunday_night', models.IntegerField(choices=[(0, '0 - Not available'), (1, '1 - Available'), (2, '2 - Preferred ')], default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)], verbose_name='sunday night 23:00-07:00')),
                ('monday_evening', models.IntegerField(choices=[(0, '0 - Not available'), (1, '1 - Available'), (2, '2 - Preferred ')], default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)], verbose_name='monday evening 16:00-23:00')),
                ('monday_night', models.IntegerField(choices=[(0, '0 - Not available'), (1, '1 - Available'), (2, '2 - Preferred ')], default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)], verbose_name='monday night 23:00-07:00')),
                ('tuesday_evening', models.IntegerField(choices=[(0, '0 - Not available'), (1, '1 - Available'), (2, '2 - Preferred ')], default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)], verbose_name='tuesday evening 16:00-23:00')),
                ('tuesday_night', models.IntegerField(choices=[(0, '0 - Not available'), (1, '1 - Available'), (2, '2 - Preferred ')], default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)], verbose_name='tuesday night 23:00-07:00')),
                ('wednesday_evening', models.IntegerField(choices=[(0, '0 - Not available'), (1, '1 - Available'), (2, '2 - Preferred ')], default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)], verbose_name='wednesday evening 16:00-23:00')),
                ('wednesday_night', models.IntegerField(choices=[(0, '0 - Not available'), (1, '1 - Available'), (2, '2 - Preferred ')], default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)], verbose_name='wednesday night 23:00-07:00')),
                ('thursday_evening', models.IntegerField(choices=[(0, '0 - Not available'), (1, '1 - Available'), (2, '2 - Preferred ')], default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)], verbose_name='thursday evening 16:00-23:00')),
                ('thursday_night', models.IntegerField(choices=[(0, '0 - Not available'), (1, '1 - Available'), (2, '2 - Preferred ')], default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)], verbose_name='thursday night 23:00-07:00')),
                ('friday_evening', models.IntegerField(choices=[(0, '0 - Not available'), (1, '1 - Available'), (2, '2 - Preferred ')], default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)], verbose_name='friday evening 15:00-23:00')),
                ('friday_night', models.IntegerField(choices=[(0, '0 - Not available'), (1, '1 - Available'), (2, '2 - Preferred ')], default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)], verbose_name='friday night 23:00-07:00')),
                ('saturday_evening', models.IntegerField(choices=[(0, '0 - Not available'), (1, '1 - Available'), (2, '2 - Preferred ')], default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)], verbose_name='saturday evening 15:00-23:00')),
                ('saturday_night', models.IntegerField(choices=[(0, '0 - Not available'), (1, '1 - Available'), (2, '2 - Preferred ')], default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)], verbose_name='saturday night 23:00-07:00')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('WeeklyDayDates', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_shifts', to='Shifts.weeklydaydates')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='shift_submitter', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
