# Generated by Django 3.2.4 on 2021-06-27 02:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='shiftSubmitTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sundayFirst', models.IntegerField(validators=[django.core.validators.MaxValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('sundaySecond', models.IntegerField(validators=[django.core.validators.MaxValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('mondayFirst', models.IntegerField(validators=[django.core.validators.MaxValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('mondaySecond', models.IntegerField(validators=[django.core.validators.MaxValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('tuesdayFirst', models.IntegerField(validators=[django.core.validators.MaxValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('tuesdaySecond', models.IntegerField(validators=[django.core.validators.MaxValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('wednesdayFirst', models.IntegerField(validators=[django.core.validators.MaxValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('wednesdaySecond', models.IntegerField(validators=[django.core.validators.MaxValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('thursdayFirst', models.IntegerField(validators=[django.core.validators.MaxValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('thursdaySecond', models.IntegerField(validators=[django.core.validators.MaxValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('fridayFirst', models.IntegerField(validators=[django.core.validators.MaxValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('fridaySecond', models.IntegerField(validators=[django.core.validators.MaxValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('saturdayFirst', models.IntegerField(validators=[django.core.validators.MaxValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('saturdaySecond', models.IntegerField(validators=[django.core.validators.MaxValueValidator(0), django.core.validators.MaxValueValidator(3)])),
            ],
        ),
    ]
