# Generated by Django 3.2.4 on 2021-07-12 01:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shifts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shiftsubmittwo',
            name='friday_evening_3pm_11pm',
        ),
        migrations.RemoveField(
            model_name='shiftsubmittwo',
            name='friday_night_11pm_7am',
        ),
        migrations.RemoveField(
            model_name='shiftsubmittwo',
            name='monday_evening_4pm_11pm',
        ),
        migrations.RemoveField(
            model_name='shiftsubmittwo',
            name='monday_night_11pm_7am',
        ),
        migrations.RemoveField(
            model_name='shiftsubmittwo',
            name='saturday_evening_3pm_11pm',
        ),
        migrations.RemoveField(
            model_name='shiftsubmittwo',
            name='saturday_night_11pm_7am',
        ),
        migrations.RemoveField(
            model_name='shiftsubmittwo',
            name='sunday_evening_4pm_11pm',
        ),
        migrations.RemoveField(
            model_name='shiftsubmittwo',
            name='sunday_night_11pm_7am',
        ),
        migrations.RemoveField(
            model_name='shiftsubmittwo',
            name='thursday_evening_4pm_11pm',
        ),
        migrations.RemoveField(
            model_name='shiftsubmittwo',
            name='thursday_night_11pm_7am',
        ),
        migrations.RemoveField(
            model_name='shiftsubmittwo',
            name='tuesday_evening_4pm_11pm',
        ),
        migrations.RemoveField(
            model_name='shiftsubmittwo',
            name='tuesday_night_11pm_7am',
        ),
        migrations.RemoveField(
            model_name='shiftsubmittwo',
            name='wednesday_evening_4pm_11pm',
        ),
        migrations.RemoveField(
            model_name='shiftsubmittwo',
            name='wednesday_night_11pm_7am',
        ),
        migrations.AddField(
            model_name='shiftsubmittwo',
            name='friday_evening',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='friday evening 15:00-23:00'),
        ),
        migrations.AddField(
            model_name='shiftsubmittwo',
            name='friday_night',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='friday night 15:00-23:00'),
        ),
        migrations.AddField(
            model_name='shiftsubmittwo',
            name='monday_evening',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='monday evening 16:00-23:00'),
        ),
        migrations.AddField(
            model_name='shiftsubmittwo',
            name='monday_night',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='monday night 23:00-07:00'),
        ),
        migrations.AddField(
            model_name='shiftsubmittwo',
            name='saturday_evening',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='saturday evening 15:00-23:00'),
        ),
        migrations.AddField(
            model_name='shiftsubmittwo',
            name='saturday_night',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='saturday night 15:00-23:00'),
        ),
        migrations.AddField(
            model_name='shiftsubmittwo',
            name='sunday_evening',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='sunday evening 16:00-23:00'),
        ),
        migrations.AddField(
            model_name='shiftsubmittwo',
            name='sunday_night',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='sunday night 23:00-07:00'),
        ),
        migrations.AddField(
            model_name='shiftsubmittwo',
            name='thursday_evening',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='thursday evening 16:00-23:00'),
        ),
        migrations.AddField(
            model_name='shiftsubmittwo',
            name='thursday_night',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='thursday night 23:00-07:00'),
        ),
        migrations.AddField(
            model_name='shiftsubmittwo',
            name='tuesday_evening',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='tuesday evening 16:00-23:00'),
        ),
        migrations.AddField(
            model_name='shiftsubmittwo',
            name='tuesday_night',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='tuesday night 23:00-07:00'),
        ),
        migrations.AddField(
            model_name='shiftsubmittwo',
            name='wednesday_evening',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='wednesday evening 16:00-23:00'),
        ),
        migrations.AddField(
            model_name='shiftsubmittwo',
            name='wednesday_night',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='wednesday night 23:00-07:00'),
        ),
    ]
