# Generated by Django 3.2.4 on 2021-07-12 02:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shifts', '0002_auto_20210712_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftsubmittwo',
            name='friday_night',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='friday night 23:00-07:00'),
        ),
        migrations.AlterField(
            model_name='shiftsubmittwo',
            name='saturday_night',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='saturday night 23:00-07:00'),
        ),
    ]
