# Generated by Django 3.2.5 on 2021-07-26 00:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shifts', '0003_auto_20210712_0219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftsubmittwo',
            name='friday_evening',
            field=models.IntegerField(choices=[(0, '0 - Not available'), (1, '1 - Available'), (2, '2 - Preferred ')], default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)], verbose_name='friday evening 15:00-23:00'),
        ),
        migrations.AlterField(
            model_name='shiftsubmittwo',
            name='friday_night',
            field=models.IntegerField(choices=[(0, '0 - Not available'), (1, '1 - Available'), (2, '2 - Preferred ')], default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)], verbose_name='friday night 23:00-07:00'),
        ),
        migrations.AlterField(
            model_name='shiftsubmittwo',
            name='monday_evening',
            field=models.IntegerField(choices=[(0, '0 - Not available'), (1, '1 - Available'), (2, '2 - Preferred ')], default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)], verbose_name='monday evening 16:00-23:00'),
        ),
        migrations.AlterField(
            model_name='shiftsubmittwo',
            name='monday_night',
            field=models.IntegerField(choices=[(0, '0 - Not available'), (1, '1 - Available'), (2, '2 - Preferred ')], default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)], verbose_name='monday night 23:00-07:00'),
        ),
        migrations.AlterField(
            model_name='shiftsubmittwo',
            name='saturday_evening',
            field=models.IntegerField(choices=[(0, '0 - Not available'), (1, '1 - Available'), (2, '2 - Preferred ')], default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)], verbose_name='saturday evening 15:00-23:00'),
        ),
        migrations.AlterField(
            model_name='shiftsubmittwo',
            name='saturday_night',
            field=models.IntegerField(choices=[(0, '0 - Not available'), (1, '1 - Available'), (2, '2 - Preferred ')], default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)], verbose_name='saturday night 23:00-07:00'),
        ),
        migrations.AlterField(
            model_name='shiftsubmittwo',
            name='sunday_evening',
            field=models.IntegerField(choices=[(0, '0 - Not available'), (1, '1 - Available'), (2, '2 - Preferred ')], default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)], verbose_name='sunday evening 16:00-23:00'),
        ),
        migrations.AlterField(
            model_name='shiftsubmittwo',
            name='sunday_night',
            field=models.IntegerField(choices=[(0, '0 - Not available'), (1, '1 - Available'), (2, '2 - Preferred ')], default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)], verbose_name='sunday night 23:00-07:00'),
        ),
        migrations.AlterField(
            model_name='shiftsubmittwo',
            name='thursday_evening',
            field=models.IntegerField(choices=[(0, '0 - Not available'), (1, '1 - Available'), (2, '2 - Preferred ')], default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)], verbose_name='thursday evening 16:00-23:00'),
        ),
        migrations.AlterField(
            model_name='shiftsubmittwo',
            name='thursday_night',
            field=models.IntegerField(choices=[(0, '0 - Not available'), (1, '1 - Available'), (2, '2 - Preferred ')], default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)], verbose_name='thursday night 23:00-07:00'),
        ),
        migrations.AlterField(
            model_name='shiftsubmittwo',
            name='tuesday_evening',
            field=models.IntegerField(choices=[(0, '0 - Not available'), (1, '1 - Available'), (2, '2 - Preferred ')], default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)], verbose_name='tuesday evening 16:00-23:00'),
        ),
        migrations.AlterField(
            model_name='shiftsubmittwo',
            name='tuesday_night',
            field=models.IntegerField(choices=[(0, '0 - Not available'), (1, '1 - Available'), (2, '2 - Preferred ')], default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)], verbose_name='tuesday night 23:00-07:00'),
        ),
        migrations.AlterField(
            model_name='shiftsubmittwo',
            name='wednesday_evening',
            field=models.IntegerField(choices=[(0, '0 - Not available'), (1, '1 - Available'), (2, '2 - Preferred ')], default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)], verbose_name='wednesday evening 16:00-23:00'),
        ),
        migrations.AlterField(
            model_name='shiftsubmittwo',
            name='wednesday_night',
            field=models.IntegerField(choices=[(0, '0 - Not available'), (1, '1 - Available'), (2, '2 - Preferred ')], default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)], verbose_name='wednesday night 23:00-07:00'),
        ),
    ]
