# Generated by Django 3.2.5 on 2021-07-27 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Shifts', '0004_auto_20210727_0250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklyuserschedule',
            name='WeeklyDayDates',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserSchedule', to='Shifts.weeklydaydates'),
        ),
    ]
